import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { consultationSchema } from "@/lib/validation/consultation";
import { scoreLead } from "@/lib/leads/scoring";
import { sendLeadToN8n } from "@/lib/n8n/webhook";
import { getEmailProvider } from "@/lib/email/provider";
import { leadConfirmationEmail, leadNotificationEmail } from "@/lib/email/templates";
import { getRequestIp, rateLimit } from "@/lib/rate-limit";
import type { Lead } from "@/lib/types/database";

/**
 * Consultation intake endpoint. This is the single source of truth for the
 * full lead pipeline described in the spec:
 *
 *  1. Validate input (zod, server-side, authoritative)
 *  2. Store lead in Supabase (leads table, inserted via the service-role
 *     client — this route has already validated/rate-limited/honeypot-
 *     checked the request, so it acts as the trusted write path rather than
 *     relying on a public RLS insert policy on a sensitive table)
 *  3. lead_number is generated by the DB default
 *  4. Track conversion event (consultation_submitted, analytics_events)
 *  5-6. Send webhook to n8n / n8n processes lead (fire-and-forget, logged)
 *  7. Notify CA Marketing (internal email)
 *  8. Send prospect confirmation (email)
 *  9. Create follow-up task (lead_tasks, via service-role client since the
 *     public RLS policy only allows inserting into `leads`)
 *  10. Response drives the success state on /consultation
 */
export async function POST(request: Request) {
  const ip = getRequestIp(request);
  const { success: withinLimit } = rateLimit(`lead:${ip}`, { limit: 5, windowMs: 10 * 60_000 });
  if (!withinLimit) {
    return NextResponse.json(
      { error: "Too many submissions. Please try again later." },
      { status: 429 }
    );
  }

  let json: unknown;
  try {
    json = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = consultationSchema.safeParse(json);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid input", issues: parsed.error.flatten().fieldErrors },
      { status: 400 }
    );
  }

  // Honeypot — silently succeed without doing anything, so bots don't learn.
  if (parsed.data.company_website_url) {
    return NextResponse.json({ success: true, lead_id: null });
  }

  const input = parsed.data;
  const { score, temperature } = scoreLead(input);

  const supabase = await createClient();
  const admin = createAdminClient();
  const { data: inserted, error: insertError } = await admin
    .from("leads")
    .insert({
      full_name: input.full_name,
      business_name: input.business_name || null,
      email: input.email,
      phone: input.phone || null,
      website: input.website || null,
      industry: input.industry || null,
      business_size: input.business_size || null,
      service_needed: input.service_needed || null,
      main_challenge: input.main_challenge || null,
      desired_outcome: input.desired_outcome || null,
      budget: input.budget || null,
      message: input.message || null,
      source: "website",
      lead_score: score,
      lead_temperature: temperature,
    })
    .select("*")
    .single();

  if (insertError || !inserted) {
    console.error("[leads] insert failed", insertError?.message);
    return NextResponse.json({ error: "Failed to save your request" }, { status: 500 });
  }

  const lead = inserted as Lead;

  // Analytics: conversion event (best-effort, non-blocking for the response).
  await supabase.from("analytics_events").insert({
    event_name: "consultation_submitted",
    session_id: request.headers.get("x-session-id") || `server-${lead.id}`,
    visitor_id: request.headers.get("x-visitor-id") || `server-${lead.id}`,
    page: "/consultation",
    metadata: { lead_id: lead.id, lead_score: score, lead_temperature: temperature },
  });

  // Fire-and-forget side effects. None of these should block or fail the
  // user-facing response — the lead is already safely stored.
  const sideEffects = async () => {
    const n8nResult = await sendLeadToN8n({
      lead_id: lead.id,
      lead_number: lead.lead_number,
      name: lead.full_name,
      business: lead.business_name,
      email: lead.email,
      phone: lead.phone,
      service: lead.service_needed,
      budget: lead.budget,
      message: lead.message,
      lead_score: lead.lead_score,
      lead_temperature: lead.lead_temperature,
      source: lead.source,
    });

    const emailProvider = getEmailProvider();
    const confirmation = leadConfirmationEmail(lead);
    const notification = leadNotificationEmail(lead);

    const notifyEmail = process.env.LEAD_NOTIFICATION_EMAIL || process.env.EMAIL_FROM;

    await Promise.all([
      emailProvider.send({ to: lead.email, ...confirmation }),
      notifyEmail
        ? emailProvider.send({ to: notifyEmail, ...notification })
        : Promise.resolve(),
    ]);

    // Follow-up task + timestamps require elevated privileges (RLS restricts
    // lead_tasks/leads updates to admins) — reuse the service-role client
    // from above, server-side only, never exposed to the browser.
    try {
      await admin.from("lead_tasks").insert({
        lead_id: lead.id,
        title: `Follow up with ${lead.full_name}`,
        description: `New ${lead.lead_temperature} lead (${lead.lead_score}/100) from the consultation form.`,
        due_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        status: "pending",
      });
      await admin
        .from("leads")
        .update({
          webhook_sent_at: n8nResult.success ? new Date().toISOString() : null,
          confirmation_sent_at: new Date().toISOString(),
        })
        .eq("id", lead.id);
    } catch (err) {
      console.error("[leads] follow-up task / timestamp update failed", err);
    }
  };

  // In serverless environments without a queue, we await the side effects so
  // they aren't killed when the function returns — but the user already has
  // their lead_id at this point via the response below being sent after.
  await sideEffects().catch((err) => console.error("[leads] side effects failed", err));

  return NextResponse.json({
    success: true,
    lead_id: lead.id,
    lead_number: lead.lead_number,
  });
}
